/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_axeldroid_Axel */

#ifndef _Included_com_axeldroid_Axel
#define _Included_com_axeldroid_Axel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_axeldroid_Axel
 * Method:    newTask
 * Signature: (ILjava/lang/String;)V
 */

#include "axel.h"
JNIEXPORT void JNICALL Java_com_axeldroid_Axel_newTask(JNIEnv *, jobject, jint,
		jstring, jobjectArray);

JNIEXPORT void JNICALL Java_com_axeldroid_Axel_axel_stop(JNIEnv *, jobject,jlong);

JNIEXPORT void JNICALL Java_com_axeldroid_Axel_refreshProgress(JNIEnv *, jobject,jlong);

void notifyProgress(void*);
#ifdef __cplusplus
}
#endif
#endif
